service: brainhack-backend

plugins:
  - serverless-python-requirements
  - serverless-wsgi

custom:
  tableName: "locations-table-${self:provider.stage}"
  wsgi:
    app: app.app
    packRequirements: false
  pythonRequirements:
    dockerizePip: false #non-linux

provider:
  name: aws
  runtime: python3.7
  stage: ${opt:stage, 'dev'}
  profile: brainhack
  region: us-east-1
  memorySize: 256
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource:
        - { "Fn::GetAtt": ["LocationInfoTable", "Arn"] }
  environment:
    LOCATIONS_TABLE: ${self:custom.tableName}

functions:
  app:
    handler: wsgi_handler.handler
    events:
      - http: ANY /
      - http: "ANY {proxy+}"

resources:
  Resources:
    LocationInfoTable:
      Type: "AWS::DynamoDB::Table"
      Properties:
        AttributeDefinitions:
          - AttributeName: region
            AttributeType: S
          - AttributeName: locationId
            AttributeType: S
        KeySchema:
          - AttributeName: region
            KeyType: HASH
          - AttributeName: locationId
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.tableName}
